# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(684, 475)
        self.label_email = QtWidgets.QLabel(Form)
        self.label_email.setGeometry(QtCore.QRect(70, 100, 71, 16))
        self.label_email.setObjectName("label_email")
        self.label_password = QtWidgets.QLabel(Form)
        self.label_password.setGeometry(QtCore.QRect(70, 130, 56, 16))
        self.label_password.setObjectName("label_password")
        self.lineEdit_email = QtWidgets.QLineEdit(Form)
        self.lineEdit_email.setGeometry(QtCore.QRect(140, 100, 200, 20))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(140, 130, 100, 20))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(115, 360, 90, 30))
        self.pushButton_start.setAutoDefault(False)
        self.pushButton_start.setDefault(False)
        self.pushButton_start.setFlat(False)
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_login = QtWidgets.QPushButton(Form)
        self.pushButton_login.setGeometry(QtCore.QRect(70, 160, 100, 30))
        self.pushButton_login.setAutoDefault(False)
        self.pushButton_login.setDefault(False)
        self.pushButton_login.setFlat(False)
        self.pushButton_login.setObjectName("pushButton_login")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(360, 200, 256, 231))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_logout = QtWidgets.QPushButton(Form)
        self.pushButton_logout.setEnabled(False)
        self.pushButton_logout.setGeometry(QtCore.QRect(180, 160, 100, 30))
        self.pushButton_logout.setAutoDefault(False)
        self.pushButton_logout.setDefault(False)
        self.pushButton_logout.setFlat(False)
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.lineEdit_Gegner_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_Gegner_1.setGeometry(QtCore.QRect(70, 230, 180, 20))
        self.lineEdit_Gegner_1.setObjectName("lineEdit_Gegner_1")
        self.lineEdit_Gegner_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_Gegner_2.setGeometry(QtCore.QRect(70, 260, 180, 20))
        self.lineEdit_Gegner_2.setObjectName("lineEdit_Gegner_2")
        self.lineEdit_Gegner_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_Gegner_3.setGeometry(QtCore.QRect(70, 290, 180, 20))
        self.lineEdit_Gegner_3.setObjectName("lineEdit_Gegner_3")
        self.lineEdit_Gegner_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_Gegner_4.setGeometry(QtCore.QRect(70, 320, 180, 20))
        self.lineEdit_Gegner_4.setObjectName("lineEdit_Gegner_4")
        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setEnabled(False)
        self.pushButton_stop.setGeometry(QtCore.QRect(115, 400, 90, 30))
        self.pushButton_stop.setAutoDefault(False)
        self.pushButton_stop.setDefault(False)
        self.pushButton_stop.setFlat(False)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.lineEdit_email_receiver = QtWidgets.QLineEdit(Form)
        self.lineEdit_email_receiver.setGeometry(QtCore.QRect(140, 50, 200, 20))
        self.lineEdit_email_receiver.setObjectName("lineEdit_email_receiver")
        self.label_email_receiver = QtWidgets.QLabel(Form)
        self.label_email_receiver.setGeometry(QtCore.QRect(30, 50, 111, 20))
        self.label_email_receiver.setObjectName("label_email_receiver")
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(360, 440, 90, 30))
        self.pushButton_clear.setAutoDefault(False)
        self.pushButton_clear.setDefault(False)
        self.pushButton_clear.setFlat(False)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.checkBox_hideBrowser = QtWidgets.QCheckBox(Form)
        self.checkBox_hideBrowser.setGeometry(QtCore.QRect(360, 170, 111, 20))
        self.checkBox_hideBrowser.setObjectName("checkBox_hideBrowser")
        self.label_email_receiver_2 = QtWidgets.QLabel(Form)
        self.label_email_receiver_2.setGeometry(QtCore.QRect(10, 70, 131, 20))
        self.label_email_receiver_2.setObjectName("label_email_receiver_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_email.setText(_translate("Form", "Email"))
        self.label_password.setText(_translate("Form", "Password"))
        self.lineEdit_email.setText(_translate("Form", "florian.sprich@gmail.com"))
        self.lineEdit_password.setText(_translate("Form", "F1s3FR94?!"))
        self.pushButton_start.setText(_translate("Form", "Start"))
        self.pushButton_login.setText(_translate("Form", "Login"))
        self.pushButton_logout.setText(_translate("Form", "Logout"))
        self.lineEdit_Gegner_1.setText(_translate("Form", "SC Paderborn"))
        self.lineEdit_Gegner_2.setText(_translate("Form", "TSG 1899 Hoffenheim"))
        self.lineEdit_Gegner_3.setText(_translate("Form", "Fortuna Düsseldorf"))
        self.lineEdit_Gegner_4.setText(_translate("Form", "1. FC Union Berlin"))
        self.pushButton_stop.setText(_translate("Form", "Stop"))
        self.lineEdit_email_receiver.setText(_translate("Form", "florian.sprich@gmail.com"))
        self.label_email_receiver.setText(_translate("Form", "Email receiver"))
        self.pushButton_clear.setText(_translate("Form", "Clear"))
        self.checkBox_hideBrowser.setText(_translate("Form", "Hide Browser"))
        self.label_email_receiver_2.setText(_translate("Form", "(komma separated)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
